### ISSUE TITLE
Trying to build in esphome 2025.3.3

### ISSUE THREAD

**Issue by beeonlinecy** [paveldn/haier-esphome#90]
Hi everyone!
I am trying to build under esphome 2025.3.3 but get an error as like the component doesnt exist in my version

`
AttributeError: module 'esphome.components.climate' has no attribute 'climate_schema'
Failed config
climate.haier: [source configs/climate/haier_hon.yaml:2]
  Platform not found: 'climate.haier'. `

**Comment by paveldn** [comment]
Hi @beeonlinecy ,

It should be OK. Can you please provide more info? What is your environment docker? Python? Home Assistant plugin? Which branch are you using? Can you provide your configuration (without keys and passwords)?
